name: CI/CD for Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
        
      - name: Directory Check
        run: ls -lR /home/runner/work/aws-practice/aws-practice/

      - name: Build with Maven
        run: mvn clean package
        working-directory: /home/runner/work/aws-practice/aws-practice/aws_practice

      - name: Debug Maven Build Output
        run: ls -R /home/runner/work/aws-practice/aws-practice/aws_practice/target

      - name: Check for Artifacts
        run: |
          if [ ! -f /home/runner/work/aws-practice/aws-practice/aws_practice/target/*.jar ]; then
            echo "Error: No artifacts found in target directory."
            exit 1
          fi

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-application
          path: /home/runner/work/aws-practice/aws-practice/aws_practice/target/*.jar
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-application
          path: /home/runner/work/aws-practice/aws-practice/aws_practice/target/

      - name: Setup key
        id: setup-key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$DEPLOY_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ec2-user
          key: ${{ secrets.DEPLOY_KEY }}
          source: "/home/runner/work/aws-practice/aws-practice/aws_practice/target/*.jar"
          target: "/home/ec2-user/deployment/"
          strip_components: 6

      - name: Connect SSH and Restart Services
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ec2-user@${{ secrets.DEPLOY_HOST }} '
            SERVER_PID="$(sudo lsof -n -i :8080 -Fp | cut -c 2-)"
            sudo kill $SERVER_PID
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            nohup java -jar /home/ec2-user/deployment/target/aws_practice-0.0.1-SNAPSHOT.jar > /home/ec2-user/deployment/server.log 2>&1 </dev/null &
          '